on:
  workflow_call:

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - run: |
          VAR=(${{ secrets.ORG_SECRET }})
          if [ -z "$VAR" ]; then
            exit 1;
          fi
